server:
  port: 8072
mybatis:
  type-aliases-package: com.igeek.gmall.pojo
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://192.168.25.160:3306/gmall-study?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  dubbo:
    application:
      name: gmall-search-service
    protocol:
      name: dubbo
    registry:
      address: 192.168.25.160:2181
      protocol: zookeeper
  elasticsearch:
    jest:
      uris: http://192.168.25.156:9200
