server:
  port: 8080
mybatis:
  type-aliases-package: com.igeek.gmall.user.pojo
  .
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://192.168.25.160:3306/gmall
    username: root
    password: root