server:
  port: 8071
mybatis:
  type-aliases-package: com.igeek.gmall.pojo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  datasource:
    url: jdbc:mysql://192.168.25.160:3306/gmall-study?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  dubbo:
    application:
      name: manager-service
    protocol:
      name: dubbo
    registry:
      address: 192.168.25.160:2181
      protocol: zookeeper
  redis:
    host: 192.168.25.153
    port: 6379
    database: 0
