server:
  port: 8082

spring:
  dubbo:
    application:
      name: gmall-item-web
    protocol:
      name: dubbo
    registry:
      address: 192.168.25.160:2181
      protocol: zookeeper
      check: false
    consumer:
      timeout: 3000
      check: false
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html